name: Lighthouse

on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Wait for the Netlify Preview 🚀
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'svenjungnickel'

      - name: Audit URLs using Lighthouse 🎉
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: ${{ steps.netlify.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
