name: Lighthouse

on:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Generate project 💻
        run: npm run generate

      - name: Wait for the Netlify Preview 🚀
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'svenjungnickel'

      - name: Audit URLs using Lighthouse 🎉
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: ${{ steps.netlify.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
